Saving all logs (not just transport_test all modes); meaning now also unit_test console and link-test console.  Packaging them all up at the end into tarball instead of piecemeal (space taken by logs during the run was not the true fatal problem causing ENOSPC a week ago -- it was really SHM limits which are taken care of now).  Relatedly for UBSAN: no more attempt to use abort-on-first-error compile flag, as it led to horrible failure while compiling capnp itself during its configure step (I guess some configure script did something ultra-touchy UBSAN does not like).  Turning this negative into a positive by collecting all non-fatal UBSAN failures in logs, which are all saved now; and now grepping for those near the end, and if an UBSAN failure is found then this new step fails the pipeline.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -201,7 +201,6 @@ jobs:
               data['compiler']['gcc']['sanitizer'] = ['None', 'address', 'thread', 'memory', 'undefined']
               data['compiler']['clang']['sanitizer'] = ['None', 'address', 'thread', 'memory', 'undefined']
             conan-profile-custom-conf: |
-              # no-sanitize-recover is key for UBSAN; else error => print and continue at run-time.
               tools.build:cflags = ["-fsanitize=undefined", "-fno-omit-frame-pointer"]
               tools.build:cxxflags = ["-fsanitize=undefined", "-fno-omit-frame-pointer"]
               tools.build:sharedlinkflags = ["-fsanitize=undefined"]
@@ -468,10 +467,39 @@ jobs:
         VERBOSE=1 make install \
           --directory $GITHUB_WORKSPACE/build/${{ matrix.build-type.conan-build-type }} \
           -j${{ steps.cpu-cores.outputs.count }}
+        # Save runner space: blow away build dir after install.
+        rm -rf $GITHUB_WORKSPACE/build/${{ matrix.build-type.conan-build-type }}
 
-    # From now on use !cancelled() to try to run any demo/test that exists regardless
+    # From now on use !cancelled() to try to run any test/demo that exists regardless
     # of preceding failures if any.  Same-ish (always()) with the log-upload at the end.
     # Worst-case they'll all fail in super-basic ways and immediately; no extra harm done.
+
+    # From now on save logs in install-dir/bin/logs.  They will be tarred up and uploaded
+    # as artifacts at the end.  For those tests below that produce separate logs as files
+    # to begin-with, this is a no-brainer.  For those (as of this writing the main one
+    # is unit_test; but also the link tests produce short logs too) who use stdout/stderr
+    # the reason to do this is 2-fold.
+    #   - UBSAN in particular produces non-fatal error output about problems it detects.
+    #     We need to analyze them after the fact and fail a step below in that case to
+    #     alert developers who would then fix such new problems.
+    #     - One can also build UBSAN-mode things with -fno-sanitize-recover which would
+    #       cause abnormal program exit on *first* error.  We do not do this for these
+    #       reasons:
+    #       - It is more convenient to let it continue and thus show all problems in one
+    #         shot.
+    #       - There is a side problem: At this time compile settings, including
+    #         in UBSAN case `-fsanitize=undefined -fno-sanitize-recover`, are applied not
+    #         just to our code or 3rd party libraries but also any other stuff built
+    #         (due to setting C[XX]FLAGS in Conan profile).  Targeting just the exact
+    #         stuff we want with those is hard and a separate project/ticket.
+    #         In the meantime -fno-sanitize-recover causes completely unrealted program
+    #         halts during the very-early step, when building dependencies including
+    #         capnp; some autotools configure.sh fails crazily, and nothing can work
+    #         from that point on due to dependencies-install step failing.  So at this
+    #         time -fno-sanitize-recover is a no-go; it affects too much unrelated stuff.
+    #   - It is more consistent/convenient to get all the bulky logs in one place as an
+    #     artifact, rather than some in the pipeline output, others in the artifacts.
+    #     (This preference is subjective, yes.)
 
     - name: Run link test [`ipc_core` - Flow-IPC Core]
       if: |
@@ -479,7 +507,8 @@ jobs:
       run: |
         ${{ env.before_each_test }}
         cd $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin
-        ./ipc_core_link_test.exec
+        mkdir -p logs/ipc_core_link_test
+        ./ipc_core_link_test.exec > logs/ipc_core_link_test/console.log 2>&1
 
     - name: Run link test [`ipc_transport_structured` - Flow-IPC Structured Transport]
       if: |
@@ -487,7 +516,8 @@ jobs:
       run: |
         ${{ env.before_each_test }}
         cd $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin
-        ./ipc_transport_structured_link_test.exec
+        mkdir -p logs/ipc_transport_structured_link_test
+        ./ipc_transport_structured_link_test.exec > logs/ipc_transport_structured_link_test/console.log 2>&1
 
     # Server will exit automatically (same below).
     - name: Run link test [`ipc_session` - Flow-IPC Sessions]
@@ -496,9 +526,10 @@ jobs:
       run: |
         ${{ env.before_each_test }}
         cd $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin
-        ./ipc_session_link_test_srv.exec & 
+        mkdir -p logs/ipc_session_link_test
+        ./ipc_session_link_test_srv.exec > logs/ipc_session_link_test/srv.console.log 2>&1 &
         sleep 1
-        ./ipc_session_link_test_cli.exec
+        ./ipc_session_link_test_cli.exec > logs/ipc_session_link_test/cli.console.log 2>&1
 
     - name: Run link test [`ipc_shm` - Flow-IPC Shared Memory]
       if: |
@@ -506,9 +537,10 @@ jobs:
       run: |
         ${{ env.before_each_test }}
         cd $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin
-        ./ipc_shm_link_test_srv.exec & 
+        mkdir -p logs/ipc_shm_link_test
+        ./ipc_shm_link_test_srv.exec > logs/ipc_shm_link_test/srv.console.log 2>&1 &
         sleep 1
-        ./ipc_shm_link_test_cli.exec
+        ./ipc_shm_link_test_cli.exec > logs/ipc_shm_link_test/cli.console.log 2>&1
         
     - name: Run link test [`ipc_shm_arena_lend` - Flow-IPC SHM-jemalloc]
       if: |
@@ -516,9 +548,10 @@ jobs:
       run: |
         ${{ env.before_each_test }}
         cd $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin
-        ./ipc_shm_arena_lend_link_test_srv.exec & 
+        mkdir -p logs/ipc_shm_arena_lend_link_test
+        ./ipc_shm_arena_lend_link_test_srv.exec > logs/ipc_shm_arena_lend_link_test/srv.console.log 2>&1 &
         sleep 1
-        ./ipc_shm_arena_lend_link_test_cli.exec
+        ./ipc_shm_arena_lend_link_test_cli.exec > logs/ipc_shm_arena_lend_link_test/cli.console.log 2>&1
 
     # As of this writing this runs with high verbosity, so we do not re-run on failure
     # like the ones below.
@@ -529,11 +562,9 @@ jobs:
         ${{ env.before_each_test }}
         echo $TSAN_OPTIONS
         cd $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin
-        ./libipc_unit_test.exec ${{ matrix.build-type.gtest-unit-tests-params }}
-
-    # Runner can easily run out of space due to logs, so we tar-up log dir
-    # at the end of each step.  We also blow away the build dir, as all
-    # should be installed in install dir by then.
+        mkdir -p logs/libipc_unit_test
+        ./libipc_unit_test.exec ${{ matrix.build-type.gtest-unit-tests-params }} \
+          > logs/libipc_unit_test/console.log 2>&1
 
     # For tests below where on failure it can be very helpful to look at higher-verbosity logs,
     # any failing step is repeated with logging hiked up.  Note that formally (and practically)
@@ -549,25 +580,23 @@ jobs:
         cat <<'EOF' > $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin/run_transport_test_sc.sh
         # Script created by pipeline during job.
         echo "Log level: [$1]."
-        OUT_DIR_NAME=log_level_$1
-        OUT_DIR=runs/scripted/$OUT_DIR_NAME
         cd $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin/transport_test
+        OUT_DIR_NAME=log_level_$1
+        OUT_DIR=../logs/transport_test/scripted/$OUT_DIR_NAME
         mkdir -p $OUT_DIR
-        ./transport_test.exec scripted $OUT_DIR/transport_test.srv.log info $1 \
-          < srv-script.txt > $OUT_DIR/transport_test.srv.console.log 2>&1 &
+        ./transport_test.exec scripted $OUT_DIR/srv.log info $1 \
+          < srv-script.txt > $OUT_DIR/srv.console.log 2>&1 &
         SRV_PID=$!
         sleep 1
-        ./transport_test.exec scripted $OUT_DIR/transport_test.cli.log info $1 \
-          < cli-script.txt > $OUT_DIR/transport_test.cli.console.log 2>&1 &
+        ./transport_test.exec scripted $OUT_DIR/cli.log info $1 \
+          < cli-script.txt > $OUT_DIR/cli.console.log 2>&1 &
         CLI_PID=$!
         if wait $SRV_PID; then SRV_EC=0; else SRV_EC=$?; fi
-        echo "Server finished with code [$SRV_EC] (logs will be uploaded as artifacts)."
+        echo "Server finished with code [$SRV_EC]."
         if wait $CLI_PID; then CLI_EC=0; else CLI_EC=$?; fi
-        echo "Client finished with code [$CLI_EC] (logs will be uploaded as artifacts)."
-        cd $OUT_DIR/..
-        tar cvzf $OUT_DIR_NAME.tgz $OUT_DIR_NAME
-        rm -rf $OUT_DIR_NAME
+        echo "Client finished with code [$CLI_EC]."
         [ $SRV_EC -eq 0 ] && [ $CLI_EC -eq 0 ]
+        EOF
 
     - name: Run integration test [transport_test - Scripted mode]
       id: transport_test_scripted
@@ -597,7 +626,6 @@ jobs:
       if: |
         (!cancelled()) && (matrix.build-type.id != 'relwithdebinfo-tsan')
       run: |
-        rm -rf $GITHUB_WORKSPACE/build/${{ matrix.build-type.conan-build-type }}
         mkdir -p ~/bin/ex_srv_run ~/bin/ex_cli_run
         mkdir -p /tmp/var/run
         cp -v $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin/transport_test/transport_test.exec \
@@ -613,23 +641,20 @@ jobs:
         echo "Log level: [$1]."
         echo "Exercise sub-mode: [$2]."
         echo "Sub-mode snippet (none or 'shm-?'): [$3]."
-        OUT_DIR=$GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin/transport_test/runs/exercise/$2
+        OUT_DIR=$GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin/logs/transport_test/exercise/$2
         mkdir -p $OUT_DIR
         cd ~/bin/ex_srv_run
-        ~/bin/ex_srv.exec exercise-srv$3 $OUT_DIR/transport_test.srv.log info $1 \
-          > $OUT_DIR/transport_test.srv.console.log 2>&1 &
+        ~/bin/ex_srv.exec exercise-srv$3 $OUT_DIR/srv.log info $1 \
+          > $OUT_DIR/srv.console.log 2>&1 &
         SRV_PID=$!
         sleep 5
-        ~/bin/ex_cli.exec exercise-cli$3 $OUT_DIR/transport_test.cli.log info $1 \
-          > $OUT_DIR/transport_test.cli.console.log 2>&1 &
+        ~/bin/ex_cli.exec exercise-cli$3 $OUT_DIR/cli.log info $1 \
+          > $OUT_DIR/cli.console.log 2>&1 &
         CLI_PID=$!
         if wait $SRV_PID; then SRV_EC=0; else SRV_EC=$?; fi
-        echo "Server finished with code [$SRV_EC] (logs will be uploaded as artifacts)."
+        echo "Server finished with code [$SRV_EC]."
         if wait $CLI_PID; then CLI_EC=0; else CLI_EC=$?; fi
-        echo "Client finished with code [$CLI_EC] (logs will be uploaded as artifacts)."
-        cd $OUT_DIR/..
-        tar cvzf $2.tgz $2
-        rm -rf $2
+        echo "Client finished with code [$CLI_EC]."
         [ $SRV_EC -eq 0 ] && [ $CLI_EC -eq 0 ]
         EOF
 
@@ -690,19 +715,45 @@ jobs:
           $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin/run_transport_test_ex.sh \
             data shm_jemalloc_log_level_data -shm-j
 
-    - name: Upload logs for [transport_test - All modes]
+    # See earlier comment block about why we saved all the logs including for console-output-only tests/demos.
+    - name: Check test/demo logs for non-fatal sanitizer error(s)
       if: |
-        always() && (matrix.build-type.id != 'relwithdebinfo-tsan')
+        (!cancelled()) && (matrix.build-type.id == 'relwithdebinfo-ubsan')
+      run: |
+        cd ${{ github.workspace }}/install/${{ matrix.build-type.conan-build-type }}/bin/logs
+        # grep returns 0 if 1+ found, 1 if none found, 2+ on error.  So check results explicitly instead of -e.
+        # Namely, for us, the only OK result is an empty stdout and empty stderr.
+        # Otherwise either grep failed (unlikely) or found 1+ problems; either way redirection target will
+        # be not-empty, and we will force failure.
+        grep 'SUMMARY: UndefinedBehaviorSanitizer:' `find . -type f` > san_failure_summaries.txt 2>&1 || true
+        if [ -s san_failure_summaries.txt ]; then
+          echo "Error(s) found.  Pipeline will fail.  Failures summarized below."
+          echo "Please peruse uploaded log artifacts, resolve the issues, and run pipeline again."
+          echo "---"
+          cat san_failure_summaries.txt
+          false
+        fi
+        echo "No errors found in logs."
+
+    - name: Package test/demo logs tarball
+      run: |
+        cd $GITHUB_WORKSPACE/install/${{ matrix.build-type.conan-build-type }}/bin
+        tar cvzf logs.tgz logs
+        rm -rf logs # Save runner space.
+
+    - name: Upload test/demo logs (please inspect if failure(s) seen above)
+      if: |
+        always()
       uses: actions/upload-artifact@v3
       with:
-        name: ipc-transport-test-run-${{ matrix.compiler.id }}-${{ matrix.build-type.id }}
+        name: ipc-logs-${{ matrix.compiler.id }}-${{ matrix.build-type.id }}
         path: |
-          ${{ github.workspace }}/install/${{ matrix.build-type.conan-build-type }}/bin/transport_test/runs
+          ${{ github.workspace }}/install/${{ matrix.build-type.conan-build-type }}/bin/logs.tgz
 
 # TODO: Look into the topic of debuggability in case of a crash.  Is a core generated?  Is it saved?
 # Do we need to manually save it as an artifact?  For that matter we would then need the binary and
 # ideally the source.  For now we save any logs that are not printed to console, and where possible
-# our demos/tests keep it the console exclusively (but in some cases, such as transport_test, it
+# our tests/demos keep it the console exclusively (but in some cases, such as transport_test, it
 # is not practical due to parallel execution and other aspects).  In general it is always better that
 # logs are sufficient; but look into situations where they are not.
 #
